project_name: sail

version: 2

release:
  prerelease: auto
  draft: true # we only publish after the Windows MSI gets uploaded
  name_template: "SailPoint CLI {{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - id: windows
    goos: [windows]
    goarch: ['386', amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: linux
    goos: [linux]
    goarch: ['386', arm, amd64, arm64]
    env:
      - CGO_ENABLED=0

  - id: macos
    binary: bin/sail
    main: ./
    goos: [darwin]
    goarch: [amd64, arm64]

archives:
  - id: nix
    builds: [macos, linux]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ replace .Os "darwin" "macos" }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      
  - id: windows
    ids: [windows]
    format_overrides:
      - formats: [ 'zip' ]
        goos: 'windows'
    wrap_in_directory: true
    files:
      - LICENSE
nfpms:
  - license: MIT
    maintainer: SailPoint
    homepage: https://github.com/sailpoint-oss/sailpoint-cli
    bindir: /usr
    description: The SailPoint Command Line Interface.
    formats:
      - deb
      - rpm