project_name: sail

version: 2

release:
  prerelease: auto
  draft: true # we only publish after the Windows MSI gets uploaded
  name_template: "SailPoint CLI {{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    main: ./main.go
    binary: bin/sail
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    goarm: ['6']
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    ids: [default]
    formats: tar.gz
    format_overrides:
      - formats: [ 'zip' ]
        goos: 'windows'
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
