project_name: sail

version: 2

release:
  prerelease: auto
  draft: true # we only publish after the Windows MSI gets uploaded
  name_template: "SailPoint CLI {{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    main: ./main.go
    binary: sail
    goos: [linux]
    goarch: ['386', arm, arm64]
    env:
      - CGO_ENABLED=0
    goarm: ['6']
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    ids: [default]
    formats: tar.gz
    format_overrides:
      - formats: [ 'zip' ]
        goos: 'windows'
    wrap_in_directory: true
    files:
      - LICENSE
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ replace .Os "darwin" "macos" }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'