project_name: sail

version: 2

release:
  prerelease: auto
  draft: true # we only publish after the Windows MSI gets uploaded
  name_template: "SailPoint CLI {{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    main: ./main.go
    binary: bin/sail
    goos: [linux, darwin, windows]
    goarch: ['386', arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
    goarm: ['6']
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    ids: [default]
    formats: tar.gz
    format_overrides:
      - formats: [ 'zip' ]
        goos: 'windows'
    wrap_in_directory: true
    files:
      - LICENSE
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ replace .Os "darwin" "macos" }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

nfpms:
  - license: MIT
    maintainer: SailPoint
    homepage: https://github.com/sailpoint-oss/sailpoint-cli
    bindir: /usr
    description: The SailPoint Command Line Interface.
    formats:
      - deb
      - rpm